create table public.posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  excerpt text,
  content jsonb not null default '{"type":"doc","content":[]}'::jsonb, -- TipTap document
  content_html text not null default '',                                -- cached server render of `content`
  reading_time_minutes numeric(5, 1) not null default 0,
  featured_image_id uuid references public.media (id) on delete set null,
  category_id uuid references public.categories (id) on delete set null,
  author_id uuid references public.profiles (id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft', 'scheduled', 'published', 'archived')),
  is_featured boolean not null default false,
  published_at timestamptz,
  scheduled_at timestamptz,
  next_article_id uuid references public.posts (id) on delete set null,
  completion_threshold_percent int check (completion_threshold_percent between 0 and 100),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  constraint posts_scheduled_requires_date
    check (status <> 'scheduled' or scheduled_at is not null),
  constraint posts_no_self_next_article
    check (next_article_id is distinct from id)
);
comment on table public.posts is 'Articles. content is the canonical TipTap JSON doc; content_html is a render cache for fast public reads.';
comment on column public.posts.completion_threshold_percent is
  'Per-article override of the global reading completion threshold (Settings -> Reading). NULL = use global default.';

create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.set_updated_at();

create index posts_status_published_idx on public.posts (status, published_at desc);
create index posts_category_id_idx on public.posts (category_id);
create index posts_author_id_idx on public.posts (author_id);
create index posts_is_featured_idx on public.posts (is_featured) where is_featured;

create table public.post_tags (
  post_id uuid not null references public.posts (id) on delete cascade,
  tag_id uuid not null references public.tags (id) on delete cascade,
  primary key (post_id, tag_id)
);
create index post_tags_tag_id_idx on public.post_tags (tag_id);

-- ============================================================================
-- The signature feature: up to 3 tracked videos embedded inline in an article.
-- ============================================================================
create table public.post_videos (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts (id) on delete cascade,
  media_id uuid references public.media (id) on delete set null,
  slot_index int not null check (slot_index between 1 and 3),
  video_key text unique, -- e.g. "article_<post_id>_video_1"; auto-generated by trigger if left null
  duration_seconds numeric(10, 3), -- dynamically detected from the media file, never hard-coded
  required boolean not null default true,
  completion_threshold_percent int not null default 90
    check (completion_threshold_percent between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (post_id, slot_index)
);
comment on table public.post_videos is
  'The (up to) 3 tracked videos embedded in an article''s content. slot_index is the Video 1/2/3 ordering.';

create trigger post_videos_set_updated_at
  before update on public.post_videos
  for each row execute function public.set_updated_at();

create or replace function public.set_post_video_key()
returns trigger
language plpgsql
as $$
begin
  if new.video_key is null then
    new.video_key := 'article_' || new.post_id::text || '_video_' || new.slot_index::text;
  end if;
  return new;
end;
$$;

create trigger post_videos_set_video_key
  before insert on public.post_videos
  for each row execute function public.set_post_video_key();

create index post_videos_post_id_idx on public.post_videos (post_id);
